import { TableType } from "@/types/tableTypes";

export const data: TableType[] = [
  {
    id: 1,
    shortUrl: "n41aCOlnx",
    longUrl: "https://www.twitter.com/tweets/8erelCoihu/",
    QrCode: {
      id: "1",
      urlId: "1",
      image: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://shrtco.de/1",
    },
    clicks: 1313,
    status: "Active",
    createdAt: "2023-10-10",
  },
  {
    id: 2,
    shortUrl: "1aCOlnj",
    longUrl: "https://www.youtube.com/watch?v=8J7ZmH0lXuk",
    QrCode: {
      id: "1",
      urlId: "1",
      image: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://shrtco.de/1",
    },
    clicks: 4313,
    status: "Inactive",
    createdAt: "2023-10-08",
  },
  {
    id: 3,
    shortUrl: "Bn4Olnxj",
    longUrl: "https://www.adventuresinwanderlust.com/",
    QrCode: {
      id: "1",
      urlId: "1",
      image: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://shrtco.de/1",
    },
    clicks: 1013,
    status: "Active",
    createdAt: "2023-10-01",
  },
  {
    id: 4,
    shortUrl: "Bn41aCOj",
    longUrl: "https://vimeo.com/625257654",
    QrCode: {
      id: "1",
      urlId: "1",
      image: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://shrtco.de/1",
    },
    clicks: 1313,
    status: "Active",
    createdAt: "2023-09-20",
  },
  {
    id: 5,
    shortUrl: "1aCOlnxj",
    longUrl: "https://unsplash.com/photos/2KjNwOzFfVQ",
    QrCode: {
      id: "1",
      urlId: "1",
      image: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://shrtco.de/1",
    },
    clicks: 1423,
    status: "Active",
    createdAt: "2023-09-18",
  },
  {
    id: 6,
    shortUrl: "n41aCOlnx",
    longUrl: "https://www.twitter.com/tweets/8erelCoihu/",
    QrCode: {
      id: "1",
      urlId: "1",
      image: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://shrtco.de/1",
    },
    clicks: 1313,
    status: "Active",
    createdAt: "2023-10-10",
  },
  {
    id: 7,
    shortUrl: "1aCOlnj",
    longUrl: "https://www.youtube.com/watch?v=8J7ZmH0lXuk",
    QrCode: {
      id: "1",
      urlId: "1",
      image: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://shrtco.de/1",
    },
    clicks: 4313,
    status: "Inactive",
    createdAt: "2023-10-08",
  },
  {
    id: 8,
    shortUrl: "Bn4Olnxj",
    longUrl: "https://www.adventuresinwanderlust.com/",
    QrCode: {
      id: "1",
      urlId: "1",
      image: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://shrtco.de/1",
    },
    clicks: 1013,
    status: "Active",
    createdAt: "2023-10-01",
  },
  {
    id: 9,
    shortUrl: "Bn41aCOj",
    longUrl: "https://vimeo.com/625257654",
    QrCode: {
      id: "1",
      urlId: "1",
      image: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://shrtco.de/1",
    },
    clicks: 1313,
    status: "Active",
    createdAt: "2023-09-20",
  },
  {
    id: 10,
    shortUrl: "1aCOlnxj",
    longUrl: "https://unsplash.com/photos/2KjNwOzFfVQ",
    QrCode: {
      id: "1",
      urlId: "1",
      image: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://shrtco.de/1",
    },
    clicks: 1423,
    status: "Active",
    createdAt: "2023-09-18",
  },
];
